apiVersion: apps/v1
kind: Deployment
metadata:
  name: display
spec:
  selector:
    matchLabels:
      app: display
  replicas: 1
  template:
    metadata:
      labels:
        app: display
    spec:
      containers:
        - name: display
          image: bshreya639/display:1.0
          env:
          - name: IP
            value: $(RESPONSE_SERVICE_SERVICE_HOST)
          - name: PORT
            value: $(RESPONSE_SERVICE_SERVICE_PORT)
          ports:
            - containerPort: 80
