apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  type: NodePort
  selector:
    app: display
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30081
