apiVersion: v1
kind: Service
metadata:
  name: response-service
spec:
  type: NodePort
  selector:
    app: response
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30080
